# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7eUvjTJ9h8wt8dekeL_OsLUawqr42Vc
"""

# /main.py

from datetime import date
from src.manager import DataManager
from src.sources.source_yahoo import YahooSource
from src.sources.source_ibkr import IBKRSource
from src.sources.source_fred import FREDSource
from src.portfolio import Portfolio


def pretty_preview(series_list, max_points=3):
    for s in series_list:
        print("="*60)
        print(f"Symbol:      {s.symbol}")
        print(f"Source:      {s.source}")
        print(f"Asset Type:  {s.asset_type}")
        print(f"Currency:    {s.currency}")
        print(f"mean_return: {s.mean_return}")
        print(f"stdev_ret.:  {s.stdev_return}")
        print(f"Puntos tot.: {len(s.data)}")
        print(f"Primeros {max_points} puntos:")
        for p in s.data[:max_points]:
            if s.asset_type == "macro":
                print(f"  {p.date} | Valor: {p.close}{s.currency}")
            else:
                print(
                    f"  {p.date} | "
                    f"O:{p.open} H:{p.high} L:{p.low} "
                    f"C:{p.close} V:{p.volume}"
                )


if __name__ == "__main__":
    # 1. Creamos fuentes
    yahoo = YahooSource()
    ibkr  = IBKRSource()
    fred  = FREDSource(api_key=None)  # opcionalmente pon tu API key de FRED

    # 2. Creamos el orquestador
    manager = DataManager(
        sources={
            "yahoo": yahoo,
            "ibkr": ibkr,
            "fred": fred,
        }
    )

    # 3. Definimos rango de fechas
    start_date = date(2025, 10, 1)
    end_date   = date(2025, 10, 10)

    # 4. Pedimos varias cosas a la vez
    reqs = [
        {
            "source": "yahoo",
            "symbols": ["AAPL", "MSFT"],
            "start": start_date,
            "end": end_date,
            "asset_type": "stock",
        },
        {
            "source": "ibkr",
            "symbols": ["TEST_INDEX"],
            "start": start_date,
            "end": end_date,
            "asset_type": "index",
        },
        {
            "source": "fred",
            "symbols": ["DFF"],  # Effective Federal Funds Rate
            "start": start_date,
            "end": end_date,
            "asset_type": "macro",
        },
    ]

    all_series = manager.fetch_multiple_sources(reqs)

    # 5. Vista previa
    pretty_preview(all_series)

    # 6. Creamos una cartera de ejemplo con 2 activos reales (AAPL/MSFT)
    #    NOTA: aquí estoy asumiendo que all_series[0] = AAPL, all_series[1] = MSFT.
    #    En código serio, haríamos una búsqueda por symbol.
    assets = {
        all_series[0].symbol: {
            "series": all_series[0],
            "weight": 0.5
        },
        all_series[1].symbol: {
            "series": all_series[1],
            "weight": 0.5
        },
    }

    portfolio = Portfolio(assets=assets)

    # 7. Report en markdown
    print("\n\n=== PORTFOLIO REPORT (Markdown) ===\n")
    print(portfolio.report(horizon_days=30))

    # 8. Plot de Monte Carlo
    # Esto abre una ventana gráfica si estás en un notebook / entorno interactivo.
    # En consola pura puede que no muestre la figura hasta que uses plt.show().
    portfolio.plots_report(days=30, n_paths=200, show_mean=True)