# -*- coding: utf-8 -*-
"""source_fred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7eUvjTJ9h8wt8dekeL_OsLUawqr42Vc
"""

from datetime import date
from typing import List, Optional
import requests

from .sources_base import BaseSource
from ..data_models import PriceSeries, PricePoint


class FREDSource(BaseSource):
    """
    Datos macroeconómicos (p.ej. tipos de interés de la Fed).
    Estos datos no tienen OHLC, solo un valor por día.
    Guardamos ese valor en 'close'.
    """
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key

    def get_price_history(
        self,
        symbols: List[str],
        start: date,
        end: date,
        asset_type: str,
    ) -> List[PriceSeries]:

        results: List[PriceSeries] = []

        for sym in symbols:
            params = {
                "series_id": sym,
                "file_type": "json",
                "observation_start": start.isoformat(),
                "observation_end": end.isoformat(),
            }
            if self.api_key:
                params["api_key"] = self.api_key

            r = requests.get(
                "https://api.stlouisfed.org/fred/series/observations",
                params=params,
                timeout=10,
            )
            payload = r.json()
            obs_list = payload.get("observations", [])

            pts: List[PricePoint] = []
            for obs in obs_list:
                d_str = obs["date"]           # "YYYY-MM-DD"
                v_str = obs["value"]          # "5.33" o "."
                try:
                    val = float(v_str)
                except ValueError:
                    val = None

                y, m, d = d_str.split("-")
                pts.append(
                    PricePoint(
                        date=date(int(y), int(m), int(d)),
                        open=None,
                        high=None,
                        low=None,
                        close=val,    # lo guardamos en close
                        volume=None,
                    )
                )

            series = PriceSeries(
                symbol=sym,
                source="fred",
                asset_type=asset_type,  # "macro"
                currency="%",           # muchas series como tipos de interés van en %
                data=pts,
            )
            results.append(series)

        return results