# -*- coding: utf-8 -*-
"""Source_yahoo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2iqFbdDnXDD1TiE_AlEbThSE3KDbMh4
"""

from datetime import date
from typing import List
import yfinance as yf

from .sources_base import BaseSource
from ..data_models import PriceSeries, PricePoint


class YahooSource(BaseSource):
    """
    Fuente real de datos de mercado usando yfinance.
    """

    def get_price_history(
        self,
        symbols: List[str],
        start: date,
        end: date,
        asset_type: str,
    ) -> List[PriceSeries]:

        results: List[PriceSeries] = []

        for sym in symbols:
            df = yf.download(
                sym,
                start=start.isoformat(),
                end=end.isoformat(),
                progress=False,
                interval="1d",
                auto_adjust=False,
            )

            tkr = yf.Ticker(sym)
            try:
                currency = tkr.fast_info["currency"]
            except Exception:
                currency = "USD"

            points: List[PricePoint] = []
            for idx, row in df.iterrows():
                points.append(
                    PricePoint(
                        date=idx.date(),
                        open=float(row.get("Open")) if row.get("Open") is not None else None,
                        high=float(row.get("High")) if row.get("High") is not None else None,
                        low=float(row.get("Low")) if row.get("Low") is not None else None,
                        close=float(row.get("Close")) if row.get("Close") is not None else None,
                        volume=float(row.get("Volume")) if row.get("Volume") is not None else None,
                    )
                )

            series = PriceSeries(
                symbol=sym,
                source="yahoo",
                asset_type=asset_type,
                currency=currency,
                data=points,
            )
            results.append(series)

        return results